### ISSUE TITLE
Doublepresso with current ASMJit compile problems

### ISSUE THREAD

**Issue by nelson2005** [tartakynov/mathpresso#2]
It looks like asmjit has evolved quite a bit since the doublepresso fork... for example, the asmjit namespace seems to have changed, Emittable isn't a part of the asmjit repository, and more.

Is there any hope of getting doublepresso updated to the current asmjit?

**Comment by tartakynov** [comment]
I plan to update doublepresso to the current asmjit during christmas holidays, hope it's not too late for you. And if it is, I would appreciate any help

**Comment by nelson2005** [comment]
I think it will be too late, I had been hoping to use it in a project for a while but didn't realize that it didn't work with newer asmjit.

I looked through the code pretty well while trying to get it to compile, seeing if it wouldn't be too hard to fix up.  I think it's too hard for me.

It is a cool project, though.

**Comment by nelson2005** [comment]
Is there any place to download an asmjit that does work  with this version?  Maybe in the future, appending the asmjit that works with doublepresso on the doublepresso site would help make sure a bulidable version could be downloaded.  Just a thought.

**Comment by tartakynov** [comment]
Ok, try this https://code.google.com/p/muparser/source/browse/branches/muParserSSE/asmjit/?r=6#asmjit%2FAsmJit-0.8.6%2FAsmJit hope it will help you, but honestly I'm not sure

**Comment by nelson2005** [comment]
thanks for the tip!

**Comment by kobalicek** [comment]
I put a refactored mathpresso here:

  https://github.com/kobalicek/mathpresso-ng

It's not completely up to date with DoublePresso, I didn't have much time to check out the changes. However, I updated it to use doubles and it works for all test cases that were part of the original MathPresso. I'm planning to open-source MPSL soon, even unfinished.
